import { spawnSync } from "node:child_process";
import {
  cpSync,
  existsSync,
  mkdirSync,
  readFileSync,
  rmSync,
  writeFileSync,
} from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const apiDir = join(root, "src", "app", "api");
const apiBackup = join(root, "src", "app", "_api.static-backup");
const outDir = join(root, "out");
const htaccessSrc = join(root, "deploy", "htaccess");
const phpSrc = join(root, "deploy", "api");

function run(command, args, env = {}) {
  const result = spawnSync(command, args, {
    cwd: root,
    stdio: "inherit",
    env: { ...process.env, ...env },
    shell: true,
  });
  if (result.status !== 0) {
    process.exit(result.status ?? 1);
  }
}

function removePath(path) {
  if (!existsSync(path)) return;
  rmSync(path, { recursive: true, force: true, maxRetries: 5, retryDelay: 200 });
}

/** Load KEY=VALUE pairs from .env.local into process.env (does not override existing). */
function loadEnvLocal() {
  const envPath = join(root, ".env.local");
  if (!existsSync(envPath)) return;
  for (const line of readFileSync(envPath, "utf8").split(/\r?\n/)) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith("#")) continue;
    const eq = trimmed.indexOf("=");
    if (eq <= 0) continue;
    const key = trimmed.slice(0, eq).trim();
    let value = trimmed.slice(eq + 1).trim();
    if (
      (value.startsWith('"') && value.endsWith('"')) ||
      (value.startsWith("'") && value.endsWith("'"))
    ) {
      value = value.slice(1, -1);
    }
    if (process.env[key] === undefined) process.env[key] = value;
  }
}

function phpString(value) {
  return String(value ?? "").replace(/\\/g, "\\\\").replace(/'/g, "\\'");
}

function writeLocalPhpConfig(apiOut) {
  const resendKey =
    process.env.RESEND_API_KEY?.trim() ||
    process.env.CPANEL_RESEND_API_KEY?.trim() ||
    "";
  const recipient =
    process.env.AUDIT_RECIPIENT?.trim() || "info@arsyconsulting.com";
  const fromEmail =
    process.env.AUDIT_FROM_EMAIL?.trim() || "noreply@arsyconsulting.com";
  const fromName = process.env.AUDIT_FROM_NAME?.trim() || "Arsy Audit Form";

  const localConfig = join(apiOut, "config.local.php");
  if (existsSync(localConfig)) removePath(localConfig);

  if (!resendKey) {
    console.log(
      "No RESEND_API_KEY in env/.env.local — upload out/ then create api/config.local.php on the server.",
    );
    return;
  }

  writeFileSync(
    localConfig,
    `<?php\n` +
      `/** Generated by build:cpanel from .env.local — do not commit. */\n` +
      `return [\n` +
      `  'recipient' => '${phpString(recipient)}',\n` +
      `  'from_email' => '${phpString(fromEmail)}',\n` +
      `  'from_name' => '${phpString(fromName)}',\n` +
      `  'resend_api_key' => '${phpString(resendKey)}',\n` +
      `];\n`,
  );
  console.log("Wrote out/api/config.local.php (from RESEND_API_KEY).");
}

loadEnvLocal();

let backedUp = false;

try {
  if (existsSync(apiDir)) {
    removePath(apiBackup);
    cpSync(apiDir, apiBackup, { recursive: true });
    removePath(apiDir);
    backedUp = true;
    console.log("Temporarily removed src/app/api (not supported by static export).");
  }

  run("npx", ["next", "build"], { DEPLOY_TARGET: "cpanel" });

  if (!existsSync(outDir)) {
    console.error("Build finished but out/ was not created.");
    process.exit(1);
  }

  const apiOut = join(outDir, "api");
  mkdirSync(apiOut, { recursive: true });
  cpSync(phpSrc, apiOut, { recursive: true });
  cpSync(htaccessSrc, join(outDir, ".htaccess"));

  const example = join(apiOut, "config.example.php");
  if (!existsSync(example)) {
    writeFileSync(
      example,
      "<?php\n// Copy to config.local.php on the server and fill in values.\n",
    );
  }

  writeLocalPhpConfig(apiOut);

  console.log("\nCPanel build ready in out/");
  console.log("Upload the contents of out/ to public_html (or ~/arsycons/).");
} finally {
  if (backedUp && existsSync(apiBackup)) {
    removePath(apiDir);
    cpSync(apiBackup, apiDir, { recursive: true });
    removePath(apiBackup);
    console.log("Restored src/app/api.");
  }
}
